export const GAME_CONFIG = {
  ROUNDS_COUNT: 3,
  ROUND_DURATION_MS: 60 * 1000, // 60 seconds
  ITEMS_PER_ROUND: 6,
  REFERENCE_COLLECTION_SIZE: 15,
  MIN_CORRECT_ITEMS: 3,
  MIN_WRONG_ITEMS: 15, // 5 wrong items per round x 3 rounds
  CHOICES_PER_ROW_MOBILE: 2,
  CHOICES_PER_ROW_DESKTOP: 3,
  REFERENCE_ITEMS_PER_ROW_MOBILE: 3,
  REFERENCE_ITEMS_PER_ROW_DESKTOP: 5,
} as const

export const ANIMATION_DURATIONS = {
  ITEM_HOVER: 200,
  ITEM_SELECTION: 300,
  ROUND_TRANSITION: 500,
  SUCCESS_CELEBRATION: 800,
  TIMER_WARNING: 150,
} as const

export const BREAKPOINTS = {
  mobile: '320px',
  tablet: '768px', 
  desktop: '1024px'
} as const