export const GAME_CONFIG = {
  ROUNDS_COUNT: 3,
  ROUND_DURATION_MS: 60 * 1000, // 60 seconds
  CARDS_PER_ROUND: 4,
  REFERENCE_DECK_SIZE: 15,
  MIN_CORRECT_CARDS: 3,
  MIN_WRONG_CARDS: 9,
  CHOICES_PER_ROW_MOBILE: 2,
  CHOICES_PER_ROW_DESKTOP: 4,
  REFERENCE_CARDS_PER_ROW_MOBILE: 3,
  REFERENCE_CARDS_PER_ROW_DESKTOP: 5,
} as const

export const ANIMATION_DURATIONS = {
  CARD_HOVER: 200,
  CARD_SELECTION: 300,
  ROUND_TRANSITION: 500,
  SUCCESS_CELEBRATION: 800,
  TIMER_WARNING: 150,
} as const

export const BREAKPOINTS = {
  mobile: '320px',
  tablet: '768px', 
  desktop: '1024px'
} as const